site_name: Pragma - Architecture Decision Records
site_description: Architecture Decision Records for [Project Name]
site_author: Architect-Team 
site_url: https://github.com/somospragma/ACP-ADR-template

# Copyright
copyright: Copyright &copy; 2025 [Pragma - Account Name]

# Navigation
nav:
  - Home: index.md
  - Getting Started:
    - Overview: getting-started/overview.md
    - How to Use ADRs: getting-started/how-to-use.md
    - Contributing: getting-started/contributing.md
  - Architecture Decisions:
    - All ADRs: adr/index.md
    - Architecture:
      - adr/architecture/index.md 
      - Architecture Style: adr/architecture/001-architecture-style.md
      - Architecture Characteristics: adr/architecture/002-architecture-goals.md  
    - Infrastructure:
      - adr/infrastructure/index.md
      - Cloud Provider: adr/infrastructure/001-choose-cloud-provider.md
      - CI/CD Pipeline: adr/infrastructure/002-Choose-devops-platform.md
      - Monitoring Solution: adr/infrastructure/003-setup-monitoring-solution.md
      - Container Orchestration: adr/infrastructure/004-choose-kubernetes.md
      - Infrastructure as Code: adr/infrastructure/005-adopt-terraform.md
    - Backend:
      - adr/backend/index.md
      - Programming Language: adr/backend/001-choose-programming-language.md
      - Web Framework: adr/backend/002-select-web-framework.md
      - Caching Strategy: adr/backend/003-implement-caching-strategy.md
    - Frontend:
      - adr/frontend/index.md
      - Frontend Framework: adr/frontend/001-choose-frontend-framework.md
      - State Management: adr/frontend/002-implement-state-management.md
      - Build Toolchain: adr/frontend/003-setup-build-toolchain.md
    - Data:
      - adr/data/index.md
      - Database Technology: adr/data/001-choose-database-technology.md
      - Data Migration: adr/data/002-design-data-migration-strategy.md
      - Backup Solution: adr/data/003-implement-data-backup-solution.md
    - Security:
      - adr/security/index.md
      - Security Framework: adr/security/001-implement-security-framework.md
      - Encryption Strategy: adr/security/002-data-encryption-approach.md
      - Access Control: adr/security/003-implement-rbac.md
    - Testing:
      - adr/testing/index.md
      - Testing Strategy: adr/testing/001-define-testing-strategy.md
      - Test Automation: adr/testing/002-setup-test-automation.md
      - Performance Testing: adr/testing/003-implement-performance-testing.md  
  - References:
    - Glossary: references/glossary.md
    - Decision Matrix: references/decision-matrix.md
    - Status Overview: references/status-overview.md
# End of Navigation
# Theme configuration
theme: readthedocs 